#!/bin/bash

set -e

bundle install

sudo installer -pkg script/SwiftCov.pkg -target /

if [ -z "$GITHUB_ACCESS_TOKEN" ]
then
  carthage bootstrap
else
  echo "-> Installing forked version of carthage"
  echo ""
  sudo installer -pkg script/Carthage.pkg -target /

  carthage bootstrap --github-access-token "$GITHUB_ACCESS_TOKEN"
fi
